{
 "title": "Custom Exporter (External API)",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Max Wind Speed (30m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max_over_time(weather_wind_speed_mps[30m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Temperature (1h)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(weather_temperature_celsius[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature Difference",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_temp_difference", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Visibility (km)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_visibility_meters / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cloud Cover (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_cloudiness_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Wind Speed (m/s)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_wind_speed_mps", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pressure (hPa)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_pressure_hpa", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Humidity (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_humidity_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Feels Like (°C)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_feels_like_celsius ", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temperature (°C)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_temperature_celsius * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}